### ISSUE TITLE
Black Screen on Android Client

### ISSUE THREAD

**Issue by LeifBloomquist** [ricardoquesada/unijoysticle#4]
Galaxy S7 with Android 6.01.

Connects to the unijoysticle-xxx AP just fine.

After I select the mode and port though, I press Start and the screen goes black.  Nothing happens after that, and I have to kill the app.  Waited several minutes.

Same behaviour with all modes.

Settings are untouched, Server IP is 192.168.4.1 .    (My phone picks up the IP 192.168.4.2)

**Comment by LeifBloomquist** [comment]
As a test I tried connecting with my laptop, and I can ping 192.168.4.1 .

**Comment by ricardoquesada** [comment]
Mmmm... strange, your phone should have an IP like 192.168.4.2... I think the mask is 255.255.255.0, thanks why it is strange that you have 192.168.7.2.

What firmware version are you using ? the one that came pre-installed?
The latest one (which includes a webserver and supports Station mode) might be easier to test.

**Comment by ricardoquesada** [comment]
Also, do you see two LEDs turned on in the NodeMCU?

**Comment by LeifBloomquist** [comment]
Sorry!  That was a typo.  Phone is indeed 192.168.4.2 .  Updated original post.

**Comment by LeifBloomquist** [comment]
Yes, two LEDs.

**Comment by ricardoquesada** [comment]
Ok, that's good.
~~Could you go to Settings? What is the server address? is it 192.168.4.1?~~
Also, what version do you have installed ? (scroll down in Settings, and you should see it in About)

**Comment by LeifBloomquist** [comment]
Settings are untouched, Server IP is 192.168.4.1 .

Version v0.4.6

**Comment by ricardoquesada** [comment]
ok. thanks.
how familiar are you with Android debugging?
I just need you to open a "logcat" to see the debug ouput. Are you familiar with logcat? (it is built-in in Android Studio)

**Comment by ricardoquesada** [comment]
f@ck!... I can reproduce the bug... my bad. I tested v0.4.6 using "unijoysticle.local" as the server... but in order to test that you need install the latest firmware...

I'll upload a new version to the Google Play in a few hours and should be online in two hours. Sorry for the inconvenience!

**Comment by LeifBloomquist** [comment]
OK cool.   I should update the firmware anyhoo.  So much for my chance to learn logcat and adb ;-)

**Comment by LeifBloomquist** [comment]
Or can you email me the .apk for a quick test?

**Comment by ricardoquesada** [comment]
sure!, I'll send you the .apk via email
